-- ============================================================================
-- Sophon-Stream Web Management System - Initial Schema Migration
-- Version: V1
-- Description: Creates all database tables for the initial release
-- ============================================================================

-- ── Users Table ─────────────────────────────────────────────────────────────
-- Stores user accounts with hashed passwords and role-based access control.
-- Roles: admin (full access), operator (device/task/algo management), viewer (read-only)
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'operator' CHECK (role IN ('admin', 'operator', 'viewer')),
    real_name TEXT,
    email TEXT,
    phone TEXT,
    status INTEGER NOT NULL DEFAULT 1 CHECK (status IN (0, 1)),  -- 1=active, 0=disabled
    last_login_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now','localtime')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);

-- ── Devices Table ──────────────────────────────────────────────────────────
-- Video source devices: IPC cameras, NVRs, RTSP streams, file sources, GB28181
-- Status: 0=offline, 1=online, 2=error
CREATE TABLE IF NOT EXISTS devices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('ipc', 'nvr', 'rtsp', 'file', 'gb28181')),
    stream_url TEXT NOT NULL,
    protocol TEXT,                          -- rtsp / rtmp / http / gb28181
    resolution TEXT,
    fps REAL DEFAULT 25.0,
    codec TEXT DEFAULT 'H.264',
    status INTEGER NOT NULL DEFAULT 0 CHECK (status IN (0, 1, 2)),
    location TEXT,
    description TEXT,
    device_id TEXT,                         -- GB28181 device ID
    last_heartbeat TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now','localtime')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);

CREATE INDEX IF NOT EXISTS idx_devices_type ON devices(type);
CREATE INDEX IF NOT EXISTS idx_devices_status ON devices(status);
CREATE INDEX IF NOT EXISTS idx_devices_device_id ON devices(device_id);

-- ── Algorithms Table ───────────────────────────────────────────────────────
-- AI inference algorithms: detection, classification, segmentation, etc.
-- Status: 1=active, 0=disabled
CREATE TABLE IF NOT EXISTS algorithms (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('detection', 'classification', 'segmentation', 'pose', 'ocr', 'face', 'tracking')),
    model_path TEXT NOT NULL,
    config_json TEXT,                       -- JSON string with algorithm-specific config
    version TEXT,
    description TEXT,
    input_size TEXT,                        -- e.g. "640x640"
    classes TEXT,                           -- JSON array of class names
    status INTEGER NOT NULL DEFAULT 1 CHECK (status IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT (datetime('now','localtime')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);

CREATE INDEX IF NOT EXISTS idx_algorithms_type ON algorithms(type);
CREATE INDEX IF NOT EXISTS idx_algorithms_status ON algorithms(status);

-- ── Tasks Table ────────────────────────────────────────────────────────────
-- Analysis tasks: each task represents a running graph pipeline.
-- Status: 0=stopped, 1=running, 2=paused, 3=error
CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    status INTEGER NOT NULL DEFAULT 0 CHECK (status IN (0, 1, 2, 3)),
    device_id INTEGER NOT NULL,
    algorithm_ids TEXT NOT NULL,            -- JSON array of algorithm IDs
    graph_config TEXT,                      -- JSON graph/DAG configuration
    schedule_config TEXT,                   -- JSON schedule config
    roi_config TEXT,                        -- JSON ROI configuration
    osd_enabled INTEGER DEFAULT 1,          -- On-Screen Display
    record_enabled INTEGER DEFAULT 0,
    output_url TEXT,
    description TEXT,
    started_at TEXT,
    stopped_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now','localtime')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now','localtime')),
    FOREIGN KEY (device_id) REFERENCES devices(id)
);

CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_device_id ON tasks(device_id);
CREATE INDEX IF NOT EXISTS idx_tasks_type ON tasks(type);

-- ── Alerts Table ──────────────────────────────────────────────────────────
-- Alert events generated by the rule engine.
-- Level: 0=info, 1=warning, 2=critical
CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id INTEGER NOT NULL,
    rule_id INTEGER,
    type TEXT NOT NULL,
    level INTEGER NOT NULL DEFAULT 1 CHECK (level IN (0, 1, 2)),
    message TEXT NOT NULL,
    evidence_path TEXT,                     -- Screenshot/video evidence path
    metadata TEXT,                          -- JSON metadata
    acknowledged INTEGER DEFAULT 0,         -- 0=pending, 1=acknowledged
    created_at TEXT NOT NULL DEFAULT (datetime('now','localtime')),
    FOREIGN KEY (task_id) REFERENCES tasks(id)
);

CREATE INDEX IF NOT EXISTS idx_alerts_task_id ON alerts(task_id);
CREATE INDEX IF NOT EXISTS idx_alerts_type ON alerts(type);
CREATE INDEX IF NOT EXISTS idx_alerts_level ON alerts(level);
CREATE INDEX IF NOT EXISTS idx_alerts_acknowledged ON alerts(acknowledged);
CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts(created_at);

-- ── Alert Rules Table ─────────────────────────────────────────────────────
-- Alert rule definitions with conditions and notification config.
CREATE TABLE IF NOT EXISTS alert_rules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    task_id INTEGER NOT NULL,
    type TEXT NOT NULL,
    condition_json TEXT NOT NULL,           -- JSON condition definition
    debounce_ms INTEGER DEFAULT 3000,      -- Minimum interval between alerts
    enabled INTEGER DEFAULT 1,
    notify_type TEXT DEFAULT 'webhook',     -- webhook / email / sms
    notify_config TEXT,                     -- JSON notification config
    created_at TEXT NOT NULL DEFAULT (datetime('now','localtime')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now','localtime')),
    FOREIGN KEY (task_id) REFERENCES tasks(id)
);

CREATE INDEX IF NOT EXISTS idx_alert_rules_task_id ON alert_rules(task_id);
CREATE INDEX IF NOT EXISTS idx_alert_rules_enabled ON alert_rules(enabled);

-- ── Plugins Table ─────────────────────────────────────────────────────────
-- Dynamically loaded plugin modules (.so files).
-- Status: 0=inactive, 1=active
CREATE TABLE IF NOT EXISTS plugins (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    version TEXT NOT NULL,
    so_path TEXT NOT NULL,
    config_schema TEXT,                     -- JSON schema for plugin config
    description TEXT,
    author TEXT,
    type TEXT,
    status INTEGER DEFAULT 0 CHECK (status IN (0, 1)),
    checksum TEXT,                          -- SHA-256 checksum of .so file
    installed_at TEXT NOT NULL DEFAULT (datetime('now','localtime')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);

CREATE INDEX IF NOT EXISTS idx_plugins_type ON plugins(type);
CREATE INDEX IF NOT EXISTS idx_plugins_status ON plugins(status);

-- ── System Config Table ───────────────────────────────────────────────────
-- Key-value system configuration store.
CREATE TABLE IF NOT EXISTS system_config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    description TEXT,
    updated_at TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);

-- ── Audit Logs Table ──────────────────────────────────────────────────────
-- Audit trail for all system operations.
CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    action TEXT NOT NULL,                   -- create / update / delete / login / logout / etc.
    resource_type TEXT NOT NULL,            -- user / device / task / algorithm / plugin / system
    resource_id INTEGER,
    detail TEXT,                            -- JSON detail of the operation
    ip_address TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now','localtime')),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource_type ON audit_logs(resource_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);

-- ── Firmware Versions Table ───────────────────────────────────────────────
-- Firmware packages for device updates.
-- Status: 0=available, 1=installed, 2=failed
CREATE TABLE IF NOT EXISTS firmware_versions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    version TEXT NOT NULL,
    type TEXT NOT NULL,                     -- system / tpu / device
    package_url TEXT,
    checksum TEXT,
    size INTEGER,
    description TEXT,
    status INTEGER DEFAULT 0 CHECK (status IN (0, 1, 2)),
    installed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);

CREATE INDEX IF NOT EXISTS idx_firmware_versions_type ON firmware_versions(type);
CREATE INDEX IF NOT EXISTS idx_firmware_versions_status ON firmware_versions(status);

-- ── Schema Migrations Table ───────────────────────────────────────────────
-- Tracks which migrations have been applied.
CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    description TEXT,
    applied_at TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);
